    {"ToByte", (PyCFunction)PyHirschPixVal_ToByte, METH_NOARGS, "ToByte()\n\n" },
    {"ToFloat", (PyCFunction)PyHirschPixVal_ToFloat, METH_NOARGS, "ToFloat()\n\n" },
    {"ToInt1", (PyCFunction)PyHirschPixVal_ToInt1, METH_NOARGS, "ToInt1()\n\n" },
    {"ToInt4", (PyCFunction)PyHirschPixVal_ToInt4, METH_NOARGS, "ToInt4()\n\n" },
    {"ToUInt2", (PyCFunction)PyHirschPixVal_ToUInt2, METH_NOARGS, "ToUInt2()\n\n" },
    {"ToComplexD", (PyCFunction)PyHirschPixVal_ToComplexD, METH_NOARGS, "ToComplexD()\n\n" },
    {"ToInt2", (PyCFunction)PyHirschPixVal_ToInt2, METH_NOARGS, "ToInt2()\n\n" },
    {"Delete", (PyCFunction)PyHirschPixVal_Delete, METH_NOARGS, "Delete()\n\n" },