// Autogenerated file for halcon type HImageArray

#include "pyhirsch.h"

static void
PyHirschImageArray_dealloc(PyHirschImageArray* self)
{
    if(self->ImageArray)
        delete self->ImageArray;
    PyObject_Del(self);
}

static int
PyHirschImageArray_init(PyHirschImageArray *self, PyObject */*args*/, PyObject */*kwds*/)
{
    // TBD - Use PyArg_ParseTupleAndKeywords() to do special initilaziation
    self->ImageArray=new Halcon::HImageArray;
    return 0;
}

#include "himagearray_autogen_methods_declarations.i"

static PyMethodDef PyHirschImageArray_methods[] = {
#include "himagearray_autogen_methods_list.i"
    {NULL}  /* Sentinel */
};

PyObject *PyHirschImageArray_FromHImageArray(Halcon::HImageArray ImageArray)
{
    PyHirschImageArray *v = (PyHirschImageArray*)PyObject_New(PyHirschImageArray, &PyHirschImageArrayType);
    v->ImageArray = new Halcon::HImageArray(ImageArray);
    return (PyObject*)v;
}

PyTypeObject PyHirschImageArrayType = {
    PyObject_HEAD_INIT(NULL)
    0,                         /*ob_size*/
    "Hirsch.HImageArray",      /*tp_name*/
    sizeof(PyHirschImageArray), /*tp_basicsize*/
    0,                         /*tp_itemsize*/
    (destructor)PyHirschImageArray_dealloc,       /*tp_dealloc*/
    0,                         /*tp_print*/
    0,                         /*tp_getattr*/
    0,                         /*tp_setattr*/
    0,                         /*tp_compare*/
    0,                         /*tp_repr*/
    0,                         /*tp_as_number*/
    0,        /*tp_as_sequence*/
    0,                         /*tp_as_mapping*/
    0,                         /*tp_hash */
    0,                         /*tp_call*/
    0,                         /*tp_str*/
    0,                         /*tp_getattro*/
    0,                         /*tp_setattro*/
    0,                         /*tp_as_buffer*/
    Py_TPFLAGS_DEFAULT,        /*tp_flags*/
    "PyHirschImageArray",        /* tp_doc */
    0,		               /* tp_traverse */
    0,		               /* tp_clear */
    0,		               /* tp_richcompare */
    0,		               /* tp_weaklistoffset */
    0,		 /* tp_iter */
    0,         /* tp_iternext */
    PyHirschImageArray_methods,  /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)PyHirschImageArray_init,          /* tp_init */
    0,                         /* tp_alloc */
    PyType_GenericNew,         /* tp_new */
};


void PyHirschImageArrayAddToModule(PyObject *m)
{
    Py_INCREF(&PyHirschImageArrayType);
    if (PyType_Ready(&PyHirschImageArrayType) < 0)
        return;
    PyModule_AddObject(m, "HImageArray", (PyObject *)&PyHirschImageArrayType);
}

