// Autogenerated file for halcon type HImage
#ifndef HIMAGE_H
#define HIMAGE_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschImage_FromHImage(Halcon::HImage Image);

typedef struct {
    PyObject_HEAD;
    Halcon::HImage *Image;
} PyHirschImage;

#define PyHirschImage_Check(op) \
    PyObject_TypeCheck(op, &PyHirschImageType)

void PyHirschImageAddToModule(PyObject *m);

extern PyTypeObject PyHirschImageType;

#endif
