// Autogenerated file for halcon type HPoint2D
#ifndef HPOINT2D_H
#define HPOINT2D_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschPoint2D_FromHPoint2D(Halcon::HPoint2D Point2D);

typedef struct {
    PyObject_HEAD;
    Halcon::HPoint2D Point2D;
    int iter_pos;
} PyHirschPoint2D;

#define PyHirschPoint2D_Check(op) \
    PyObject_TypeCheck(op, &PyHirschPoint2DType)

void PyHirschPoint2DAddToModule(PyObject *m);

extern PyTypeObject PyHirschPoint2DType;

#endif
