// Autogenerated file for halcon type HRegion
#ifndef HREGION_H
#define HREGION_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschRegion_FromHRegion(Halcon::HRegion Region);

typedef struct {
    PyObject_HEAD;
    Halcon::HRegion *Region;
} PyHirschRegion;

#define PyHirschRegion_Check(op) \
    PyObject_TypeCheck(op, &PyHirschRegionType)

void PyHirschRegionAddToModule(PyObject *m);

extern PyTypeObject PyHirschRegionType;

#endif
