// Autogenerated file for halcon type HRectangle2
#ifndef PYHRECTANGLE2_H
#define HRECTANGLE2_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschRectangle2_FromHRectangle2(Halcon::HRectangle2 Rectangle2);

typedef struct {
    PyObject_HEAD;
    Halcon::HRectangle2 Rectangle2;
} PyHirschRectangle2;

#define PyHirschRectangle2_Check(op) \
    PyObject_TypeCheck(op, &PyHirschRectangle2Type)

void PyHirschRectangle2AddToModule(PyObject *m);

PyAPI_DATA(PyTypeObject) PyHirschRectangle2Type;

#endif
