// Autogenerated file for halcon type HTemplate

#include "pyhirsch.h"

static void
PyHirschTemplate_dealloc(PyHirschTemplate* self)
{
    if(self->Template)
        delete self->Template;
    PyObject_Del(self);
}

static int
PyHirschTemplate_init(PyHirschTemplate *self, PyObject */*args*/, PyObject */*kwds*/)
{
    // TBD - Use PyArg_ParseTupleAndKeywords() to do special initilaziation
    self->Template=new Halcon::HTemplate;
    return 0;
}

#include "htemplate_autogen_methods_declarations.i"

static PyMethodDef PyHirschTemplate_methods[] = {
#include "htemplate_autogen_methods_list.i"
    {NULL}  /* Sentinel */
};

PyObject *PyHirschTemplate_FromHTemplate(Halcon::HTemplate Template)
{
    PyHirschTemplate *v = (PyHirschTemplate*)PyObject_New(PyHirschTemplate, &PyHirschTemplateType);
    v->Template = new Halcon::HTemplate(Template);
    return (PyObject*)v;
}

PyTypeObject PyHirschTemplateType = {
    PyObject_HEAD_INIT(NULL)
    0,                         /*ob_size*/
    "Halcon.Rectangle",      /*tp_name*/
    sizeof(PyHirschTemplate), /*tp_basicsize*/
    0,                         /*tp_itemsize*/
    (destructor)PyHirschTemplate_dealloc,       /*tp_dealloc*/
    0,                         /*tp_print*/
    0,                         /*tp_getattr*/
    0,                         /*tp_setattr*/
    0,                         /*tp_compare*/
    0,                         /*tp_repr*/
    0,                         /*tp_as_number*/
    0,        /*tp_as_sequence*/
    0,                         /*tp_as_mapping*/
    0,                         /*tp_hash */
    0,                         /*tp_call*/
    0,                         /*tp_str*/
    0,                         /*tp_getattro*/
    0,                         /*tp_setattro*/
    0,                         /*tp_as_buffer*/
    Py_TPFLAGS_DEFAULT,        /*tp_flags*/
    "PyHirschTemplate",        /* tp_doc */
    0,		               /* tp_traverse */
    0,		               /* tp_clear */
    0,		               /* tp_richcompare */
    0,		               /* tp_weaklistoffset */
    0,		 /* tp_iter */
    0,         /* tp_iternext */
    PyHirschTemplate_methods,  /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)PyHirschTemplate_init,          /* tp_init */
    0,                         /* tp_alloc */
    PyType_GenericNew,         /* tp_new */
};


void PyHirschTemplateAddToModule(PyObject *m)
{
    Py_INCREF(&PyHirschTemplateType);
    if (PyType_Ready(&PyHirschTemplateType) < 0)
        return;
    PyModule_AddObject(m, "HTemplate", (PyObject *)&PyHirschTemplateType);
}
