// Autogenerated file for halcon type HXLDArray

#include "pyhirsch.h"

static void
PyHirschXLDArray_dealloc(PyHirschXLDArray* self)
{
    if(self->XLDArray)
        delete self->XLDArray;
    PyObject_Del(self);
}

static int
PyHirschXLDArray_init(PyHirschXLDArray *self, PyObject */*args*/, PyObject */*kwds*/)
{
    // TBD - Use PyArg_ParseTupleAndKeywords() to do special initilaziation
    self->XLDArray=new Halcon::HXLDArray;
    return 0;
}

#include "hxldarray_autogen_methods_declarations.i"

static PyMethodDef PyHirschXLDArray_methods[] = {
#include "hxldarray_autogen_methods_list.i"
    {NULL}  /* Sentinel */
};

PyObject *PyHirschXLDArray_FromHXLDArray(Halcon::HXLDArray XLDArray)
{
    PyHirschXLDArray *v = (PyHirschXLDArray*)PyObject_New(PyHirschXLDArray, &PyHirschXLDArrayType);
    v->XLDArray = new Halcon::HXLDArray(XLDArray);
    return (PyObject*)v;
}

PyTypeObject PyHirschXLDArrayType = {
    PyObject_HEAD_INIT(NULL)
    0,                         /*ob_size*/
    "Hirsch.HXLDArray",      /*tp_name*/
    sizeof(PyHirschXLDArray), /*tp_basicsize*/
    0,                         /*tp_itemsize*/
    (destructor)PyHirschXLDArray_dealloc,       /*tp_dealloc*/
    0,                         /*tp_print*/
    0,                         /*tp_getattr*/
    0,                         /*tp_setattr*/
    0,                         /*tp_compare*/
    0,                         /*tp_repr*/
    0,                         /*tp_as_number*/
    0,        /*tp_as_sequence*/
    0,                         /*tp_as_mapping*/
    0,                         /*tp_hash */
    0,                         /*tp_call*/
    0,                         /*tp_str*/
    0,                         /*tp_getattro*/
    0,                         /*tp_setattro*/
    0,                         /*tp_as_buffer*/
    Py_TPFLAGS_DEFAULT,        /*tp_flags*/
    "PyHirschXLDArray",        /* tp_doc */
    0,		               /* tp_traverse */
    0,		               /* tp_clear */
    0,		               /* tp_richcompare */
    0,		               /* tp_weaklistoffset */
    0,		 /* tp_iter */
    0,         /* tp_iternext */
    PyHirschXLDArray_methods,  /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)PyHirschXLDArray_init,          /* tp_init */
    0,                         /* tp_alloc */
    PyType_GenericNew,         /* tp_new */
};


void PyHirschXLDArrayAddToModule(PyObject *m)
{
    Py_INCREF(&PyHirschXLDArrayType);
    if (PyType_Ready(&PyHirschXLDArrayType) < 0)
        return;
    PyModule_AddObject(m, "HXLDArray", (PyObject *)&PyHirschXLDArrayType);
}

