// Autogenerated file for halcon type HAffineTrans2D
#ifndef PYHAFFINETRANS2D_H
#define HAFFINETRANS2D_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschAffineTrans2D_FromHAffineTrans2D(Halcon::HAffineTrans2D AffineTrans2D);

typedef struct {
    PyObject_HEAD;
    Halcon::HAffineTrans2D AffineTrans2D;
} PyHirschAffineTrans2D;

#define PyHirschAffineTrans2D_Check(op) \
    PyObject_TypeCheck(op, &PyHirschAffineTrans2DType)

void PyHirschAffineTrans2DAddToModule(PyObject *m);

extern PyTypeObject  PyHirschAffineTrans2DType;

#endif
