// Autogenerated file for halcon type HBarCode
#ifndef PYHBARCODE_H
#define PYHBARCODE_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschBarCode_FromHBarCode(HalconCpp::HBarCode BarCode);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HBarCode *BarCode;
} PyHirschBarCode;

#define PyHirschBarCode_Check(op) \
    PyObject_TypeCheck(op, &PyHirschBarCodeType)

void PyHirschBarCodeAddToModule(PyObject *m);

extern PyTypeObject PyHirschBarCodeType;

#endif
