// Autogenerated file for halcon type HCircle
#ifndef PYHCIRCLE_H
#define HCIRCLE_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschCircle_FromHCircle(Halcon::HCircle Circle);

typedef struct {
    PyObject_HEAD;
    Halcon::HCircle Circle;
} PyHirschCircle;

#define PyHirschCircle_Check(op) \
    PyObject_TypeCheck(op, &PyHirschCircleType)

void PyHirschCircleAddToModule(PyObject *m);

extern PyTypeObject  PyHirschCircleType;

#endif
