// Autogenerated file for halcon type HDataCode2D

#include "pyhirsch.h"

static void
PyHirschDataCode2D_dealloc(PyHirschDataCode2D* self)
{
    if(self->DataCode2D)
        delete self->DataCode2D;
    PyObject_Del(self);
}

static int
PyHirschDataCode2D_init(PyHirschDataCode2D *self, PyObject *args, PyObject */*kwds*/)
{
    const char *SymbolType;
    const char *GenParamNames;
    const char *GenParamValues;
    if (PyArg_ParseTuple(args, "sss",
                         &SymbolType,
                         &GenParamNames,
                         &GenParamValues))
        self->DataCode2D = new Halcon::HDataCode2D(SymbolType, GenParamNames, GenParamValues);
    else
        self->DataCode2D = new Halcon::HDataCode2D();

    return 0;
}

#include "hdatacode2d_autogen_methods_declarations.i"

static PyMethodDef PyHirschDataCode2D_methods[] = {
#include "hdatacode2d_autogen_methods_list.i"
    {NULL}  /* Sentinel */
};

PyObject *PyHirschDataCode2D_FromHDataCode2D(Halcon::HDataCode2D DataCode2D)
{
    PyHirschDataCode2D *v = (PyHirschDataCode2D*)PyObject_New(PyHirschDataCode2D, &PyHirschDataCode2DType);
    v->DataCode2D = new Halcon::HDataCode2D(DataCode2D);
    return (PyObject*)v;
}

PyTypeObject PyHirschDataCode2DType = {
    PyObject_HEAD_INIT(NULL)
    0,                         /*ob_size*/
    "Hirsch.HDataCode2D",      /*tp_name*/
    sizeof(PyHirschDataCode2D), /*tp_basicsize*/
    0,                         /*tp_itemsize*/
    (destructor)PyHirschDataCode2D_dealloc,       /*tp_dealloc*/
    0,                         /*tp_print*/
    0,                         /*tp_getattr*/
    0,                         /*tp_setattr*/
    0,                         /*tp_compare*/
    0,                         /*tp_repr*/
    0,                         /*tp_as_number*/
    0,        /*tp_as_sequence*/
    0,                         /*tp_as_mapping*/
    0,                         /*tp_hash */
    0,                         /*tp_call*/
    0,                         /*tp_str*/
    0,                         /*tp_getattro*/
    0,                         /*tp_setattro*/
    0,                         /*tp_as_buffer*/
    Py_TPFLAGS_DEFAULT,        /*tp_flags*/
    "PyHirschDataCode2D",        /* tp_doc */
    0,		               /* tp_traverse */
    0,		               /* tp_clear */
    0,		               /* tp_richcompare */
    0,		               /* tp_weaklistoffset */
    0,		 /* tp_iter */
    0,         /* tp_iternext */
    PyHirschDataCode2D_methods,  /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)PyHirschDataCode2D_init,          /* tp_init */
    0,                         /* tp_alloc */
    PyType_GenericNew,         /* tp_new */
};


void PyHirschDataCode2DAddToModule(PyObject *m)
{
    Py_INCREF(&PyHirschDataCode2DType);
    if (PyType_Ready(&PyHirschDataCode2DType) < 0)
        return;
    PyModule_AddObject(m, "HDataCode2D", (PyObject *)&PyHirschDataCode2DType);
}

