// Autogenerated file for halcon type HDataCode2D
#ifndef PYHDATACODE2D_H
#define HDATACODE2D_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschDataCode2D_FromHDataCode2D(HalconCpp::HDataCode2D DataCode2D);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HDataCode2D *DataCode2D;
} PyHirschDataCode2D;

#define PyHirschDataCode2D_Check(op) \
    PyObject_TypeCheck(op, &PyHirschDataCode2DType)

void PyHirschDataCode2DAddToModule(PyObject *m);

extern PyTypeObject PyHirschDataCode2DType;

#endif
