// Autogenerated file for halcon type HDPoint2D
#ifndef HDPOINT2D_H
#define HDPOINT2D_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschDPoint2D_FromHDPoint2D(HalconCpp::HDPoint2D DPoint2D);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HDPoint2D DPoint2D;
    int iter_pos;
} PyHirschDPoint2D;

#define PyHirschDPoint2D_Check(op) \
    PyObject_TypeCheck(op, &PyHirschDPoint2DType)

void PyHirschDPoint2DAddToModule(PyObject *m);

extern PyTypeObject PyHirschDPoint2DType;

#endif
