// Autogenerated file for Halcon type HHomMat2DArray
#ifndef PYHHOMMAT2DARRAY_H
#define PYHHOMMAT2DARRAY_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschHomMat2DArray_FromHHomMat2DArray(HalconCpp::HHomMat2DArray HomMat2DArray);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HHomMat2DArray HomMat2DArray;
} PyHirschHomMat2DArray;

#define PyHirschHomMat2DArray_Check(op) \
    PyObject_TypeCheck(op, &PyHirschHomMat2DArrayType)

void PyHirschHomMat2DArrayAddToModule(PyObject *m);

extern PyTypeObject PyHirschHomMat2DArrayType;

#endif
