// Autogenerated file for halcon type HHomMat2DArray

#include "pyhirsch.h"

static void
PyHirschHomMat2DArray_dealloc(PyHirschHomMat2DArray* self)
{
    PyObject_Del(self);
}

static int
PyHirschHomMat2DArray_init(PyHirschHomMat2DArray *self, PyObject */*args*/, PyObject */*kwds*/)
{
    // TBD - Use PyArg_ParseTupleAndKeywords() to do special initialziation
    return 0;
}

#include "hhommat2darray_autogen_methods_declarations.i"

static PyMethodDef PyHirschHomMat2DArray_methods[] = {
#include "hhommat2darray_autogen_methods_list.i"
    {NULL}  /* Sentinel */
};

PyObject *PyHirschHomMat2DArray_FromHHomMat2DArray(HalconCpp::HHomMat2DArray HomMat2DArray)
{
    PyHirschHomMat2DArray *v = (PyHirschHomMat2DArray*)PyObject_New(PyHirschHomMat2DArray, &PyHirschHomMat2DArrayType);
    v->HomMat2DArray = HalconCpp::HHomMat2DArray(HomMat2DArray);
    return (PyObject*)v;
}

PyTypeObject PyHirschHomMat2DArrayType = {
    PyObject_HEAD_INIT(NULL)
    0,                         /*ob_size*/
    "Halcon.PyHirschHomMat2DArray",      /*tp_name*/
    sizeof(PyHirschHomMat2DArray), /*tp_basicsize*/
    0,                         /*tp_itemsize*/
    (destructor)PyHirschHomMat2DArray_dealloc,       /*tp_dealloc*/
    0,                         /*tp_print*/
    0,                         /*tp_getattr*/
    0,                         /*tp_setattr*/
    0,                         /*tp_compare*/
    0,                         /*tp_repr*/
    0,                         /*tp_as_number*/
    0,        /*tp_as_sequence*/
    0,                         /*tp_as_mapping*/
    0,                         /*tp_hash */
    0,                         /*tp_call*/
    0,                         /*tp_str*/
    0,                         /*tp_getattro*/
    0,                         /*tp_setattro*/
    0,                         /*tp_as_buffer*/
    Py_TPFLAGS_DEFAULT,        /*tp_flags*/
    "PyHirschHomMat2DArray",        /* tp_doc */
    0,		               /* tp_traverse */
    0,		               /* tp_clear */
    0,		               /* tp_richcompare */
    0,		               /* tp_weaklistoffset */
    0,		 /* tp_iter */
    0,         /* tp_iternext */
    PyHirschHomMat2DArray_methods,  /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)PyHirschHomMat2DArray_init,          /* tp_init */
    0,                         /* tp_alloc */
    PyType_GenericNew,         /* tp_new */
};


void PyHirschHomMat2DArrayAddToModule(PyObject *m)
{
    Py_INCREF(&PyHirschHomMat2DArrayType);
    if (PyType_Ready(&PyHirschHomMat2DArrayType) < 0)
        return;
    PyModule_AddObject(m, "HHomMat2DArray", (PyObject *)&PyHirschHomMat2DArrayType);
}

