// Autogenerated file for halcon type HHomMat2D

#include "pyhirsch.h"

static void
PyHirschHomMat2D_dealloc(PyHirschHomMat2D* self)
{
    PyObject_Del(self);
}

static int
PyHirschHomMat2D_init(PyHirschHomMat2D *self, PyObject */*args*/, PyObject */*kwds*/)
{
    // TBD - Use PyArg_ParseTupleAndKeywords() to do special initialziation
    return 0;
}

#include "hhommat2d_autogen_methods_declarations.i"

static PyMethodDef PyHirschHomMat2D_methods[] = {
#include "hhommat2d_autogen_methods_list.i"
    {NULL}  /* Sentinel */
};

PyObject *PyHirschHomMat2D_FromHHomMat2D(HalconCpp::HHomMat2D HomMat2D)
{
    PyHirschHomMat2D *v = (PyHirschHomMat2D*)PyObject_New(PyHirschHomMat2D, &PyHirschHomMat2DType);
    v->HomMat2D = HalconCpp::HHomMat2D(HomMat2D);
    return (PyObject*)v;
}

PyTypeObject PyHirschHomMat2DType = {
    PyObject_HEAD_INIT(NULL)
    0,                         /*ob_size*/
    "Halcon.PyHirschHomMat2D",      /*tp_name*/
    sizeof(PyHirschHomMat2D), /*tp_basicsize*/
    0,                         /*tp_itemsize*/
    (destructor)PyHirschHomMat2D_dealloc,       /*tp_dealloc*/
    0,                         /*tp_print*/
    0,                         /*tp_getattr*/
    0,                         /*tp_setattr*/
    0,                         /*tp_compare*/
    0,                         /*tp_repr*/
    0,                         /*tp_as_number*/
    0,        /*tp_as_sequence*/
    0,                         /*tp_as_mapping*/
    0,                         /*tp_hash */
    0,                         /*tp_call*/
    0,                         /*tp_str*/
    0,                         /*tp_getattro*/
    0,                         /*tp_setattro*/
    0,                         /*tp_as_buffer*/
    Py_TPFLAGS_DEFAULT,        /*tp_flags*/
    "PyHirschHomMat2D",        /* tp_doc */
    0,		               /* tp_traverse */
    0,		               /* tp_clear */
    0,		               /* tp_richcompare */
    0,		               /* tp_weaklistoffset */
    0,		 /* tp_iter */
    0,         /* tp_iternext */
    PyHirschHomMat2D_methods,  /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)PyHirschHomMat2D_init,          /* tp_init */
    0,                         /* tp_alloc */
    PyType_GenericNew,         /* tp_new */
};


void PyHirschHomMat2DAddToModule(PyObject *m)
{
    Py_INCREF(&PyHirschHomMat2DType);
    if (PyType_Ready(&PyHirschHomMat2DType) < 0)
        return;
    PyModule_AddObject(m, "HHomMat2D", (PyObject *)&PyHirschHomMat2DType);
}

