// Autogenerated file for Halcon type HHomMat2D
#ifndef PYHHOMMAT2D_H
#define HHOMMAT2D_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschHomMat2D_FromHHomMat2D(HalconCpp::HHomMat2D HomMat2D);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HHomMat2D HomMat2D;
} PyHirschHomMat2D;

#define PyHirschHomMat2D_Check(op) \
    PyObject_TypeCheck(op, &PyHirschHomMat2DType)

void PyHirschHomMat2DAddToModule(PyObject *m);

extern PyTypeObject PyHirschHomMat2DType;

#endif
