// Autogenerated file for halcon type HImageArray
#ifndef PYHIMAGEARRAY_H
#define PYHIMAGEARRAY_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschImageArray_FromHImageArray(Halcon::HImageArray ImageArray);

typedef struct {
    PyObject_HEAD;
    Halcon::HImageArray *ImageArray;
    int iter_pos;
} PyHirschImageArray;

#define PyHirschImageArray_Check(op) \
    PyObject_TypeCheck(op, &PyHirschImageArrayType)

void PyHirschImageArrayAddToModule(PyObject *m);

extern PyTypeObject  PyHirschImageArrayType;

#endif
