// Autogenerated file for halcon type HRectangle1
#ifndef HRECTANGLE1_H
#define HRECTANGLE1_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschRectangle1_FromHRectangle1(Halcon::HRectangle1 Rectangle1);

typedef struct {
    PyObject_HEAD;
    Halcon::HRectangle1 Rectangle1;
    int iter_pos;
} PyHirschRectangle1;

#define PyHirschRectangle1_Check(op) \
    PyObject_TypeCheck(op, &PyHirschRectangle1Type)

void PyHirschRectangle1AddToModule(PyObject *m);

extern PyTypeObject PyHirschRectangle1Type;

#endif
