// Autogenerated file for Halcon type HRegion
#ifndef PYHREGION_H
#define PYHREGION_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschRegion_FromHRegion(const HalconCpp::HRegion& Region);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HRegion *Region;
    int iter_pos;
} PyHirschRegion;

#define PyHirschRegion_Check(op) \
    PyObject_TypeCheck(op, &PyHirschRegionType)

void PyHirschRegionAddToModule(PyObject *m);

extern PyTypeObject PyHirschRegionType;

#endif
