// Autogenerated file for halcon type HTemplate
#ifndef PYHTEMPLATE_H
#define HTEMPLATE_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschTemplate_FromHTemplate(Halcon::HTemplate Template);

typedef struct {
    PyObject_HEAD;
    Halcon::HTemplate *Template;
} PyHirschTemplate;

#define PyHirschTemplate_Check(op) \
    PyObject_TypeCheck(op, &PyHirschTemplateType)

void PyHirschTemplateAddToModule(PyObject *m);

extern PyTypeObject  PyHirschTemplateType;

#endif
