// Autogenerated file for halcon type HTuple
#ifndef PYHTUPLE_H
#define HTUPLE_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschTuple_FromHTuple(HalconCpp::HTuple Tuple);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HTuple *Tuple;
    int iter_pos;
} PyHirschTuple;

#define PyHirschTuple_Check(op) \
    PyObject_TypeCheck(op, &PyHirschTupleType)

void PyHirschTupleAddToModule(PyObject *m);

extern PyTypeObject PyHirschTupleType;

#endif
