// Autogenerated file for halcon type HXLD
#ifndef PYHXLD_H
#define HXLD_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschXLD_FromHXLD(Halcon::HXLD XLD);

typedef struct {
    PyObject_HEAD;
    Halcon::HXLD *XLD;
} PyHirschXLD;

#define PyHirschXLD_Check(op) \
    PyObject_TypeCheck(op, &PyHirschXLDType)

void PyHirschXLDAddToModule(PyObject *m);

extern PyTypeObject  PyHirschXLDType;

#endif
