// Autogenerated file for halcon type HXLDCont
#ifndef HXLDCONT_H
#define HXLDCONT_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschXLDCont_FromHXLDCont(Halcon::HXLDCont XLDCont);

typedef struct {
    PyObject_HEAD;
    Halcon::HXLDCont *XLDCont;
} PyHirschXLDCont;

#define PyHirschXLDCont_Check(op) \
    PyObject_TypeCheck(op, &PyHirschXLDContType)

void PyHirschXLDContAddToModule(PyObject *m);

extern PyTypeObject PyHirschXLDContType;

#endif
