// Autogenerated file for halcon type HXLDCont

#include "pyhirsch.h"

static void
PyHirschXLDCont_dealloc(PyHirschXLDCont* self)
{
    if(self->XLDCont)
        delete self->XLDCont;
    PyObject_Del(self);
}

static int
PyHirschXLDCont_init(PyHirschXLDCont *self, PyObject */*args*/, PyObject */*kwds*/)
{
    // TBD - Use PyArg_ParseTupleAndKeywords() to do special initialization
    self->XLDCont=new HalconCpp::HXLDCont;
    return 0;
}

#include "hxldcont_autogen_methods_declarations.i"

static PyMethodDef PyHirschXLDCont_methods[] = {
#include "hxldcont_autogen_methods_list.i"
    {NULL}  /* Sentinel */
};

Py_ssize_t PyHirschXLDCont_Length(PyObject *o)
{
    HalconCpp::HXLDCont *XLDCont = (((PyHirschXLDCont*)o)->XLDCont);
    return XLDCont->CountObj(); // Return the length of the sequence
}

PyObject *
PyHirschXLDCont_GetItem(PyObject *o, Py_ssize_t i)
{
    HalconCpp::HXLDCont *XLDCont = (((PyHirschXLDCont*)o)->XLDCont);

    try {
      return PyHirschXLDCont_FromHXLDCont(((*XLDCont)[i+1]));
    }
    catch (HalconCpp::HException &except) {
        PyErr_SetString(PyExc_RuntimeError, except.ErrorMessage().Text());
        return NULL;
    }
}

static PySequenceMethods PyHirschXLDCont_sequence_methods = {
    PyHirschXLDCont_Length,                /* sq_length */
    0,                                   /* sq_concat */
    0,                                   /* sq_repeat */
    PyHirschXLDCont_GetItem,               /* sq_item */
};


PyObject* PyHirschXLDCont_iter(PyObject *self)
{
  Py_INCREF(self);
  ((PyHirschXLDCont*)self)->iter_pos = 0;
  return self;
}

PyObject* PyHirschXLDCont_iternext(PyObject *self)
{
    PyHirschXLDCont *p = (PyHirschXLDCont *)self;
    HalconCpp::HXLDCont *XLDCont = (p->XLDCont);

    if (p->iter_pos < XLDCont->CountObj()) {
        int i=p->iter_pos; // shortcut
        p->iter_pos+=1;

        try {
          return PyHirschXLDCont_FromHXLDCont(((*XLDCont)[i+1]));
        }
        catch (HalconCpp::HException &except) {
            PyErr_SetString(PyExc_RuntimeError, except.ErrorMessage().Text());
            return NULL;
        }
    }
    else {
        /* Raising of standard StopIteration exception with empty value. */
        PyErr_SetNone(PyExc_StopIteration);
        return NULL;
    }
}

PyObject *PyHirschXLDCont_FromHXLDCont(HalconCpp::HXLDCont XLDCont)
{
    PyHirschXLDCont *v = (PyHirschXLDCont*)PyObject_New(PyHirschXLDCont, &PyHirschXLDContType);
    v->XLDCont = new HalconCpp::HXLDCont(XLDCont);
    return (PyObject*)v;
}

PyTypeObject PyHirschXLDContType = {
    PyObject_HEAD_INIT(NULL)
    0,                         /*ob_size*/
    "hirsch13.HXLDCont",      /*tp_name*/
    sizeof(PyHirschXLDCont), /*tp_basicsize*/
    0,                         /*tp_itemsize*/
    (destructor)PyHirschXLDCont_dealloc,       /*tp_dealloc*/
    0,                         /*tp_print*/
    0,                         /*tp_getattr*/
    0,                         /*tp_setattr*/
    0,                         /*tp_compare*/
    0,                         /*tp_repr*/
    0,                         /*tp_as_number*/
    &PyHirschXLDCont_sequence_methods,        /*tp_as_sequence*/
    0,                         /*tp_as_mapping*/
    0,                         /*tp_hash */
    0,                         /*tp_call*/
    0,                         /*tp_str*/
    0,                         /*tp_getattro*/
    0,                         /*tp_setattro*/
    0,                         /*tp_as_buffer*/
    Py_TPFLAGS_DEFAULT|Py_TPFLAGS_HAVE_ITER,        /*tp_flags*/
    "PyHirschXLDCont",        /* tp_doc */
    0,		               /* tp_traverse */
    0,		               /* tp_clear */
    0,		               /* tp_richcompare */
    0,		               /* tp_weaklistoffset */
    &PyHirschXLDCont_iter,		 /* tp_iter */
    &PyHirschXLDCont_iternext,         /* tp_iternext */
    PyHirschXLDCont_methods,  /* tp_methods */
    0,                         /* tp_members */
    0,                         /* tp_getset */
    0,                         /* tp_base */
    0,                         /* tp_dict */
    0,                         /* tp_descr_get */
    0,                         /* tp_descr_set */
    0,                         /* tp_dictoffset */
    (initproc)PyHirschXLDCont_init,          /* tp_init */
    0,                         /* tp_alloc */
    PyType_GenericNew,         /* tp_new */
};


void PyHirschXLDContAddToModule(PyObject *m)
{
    Py_INCREF(&PyHirschXLDContType);
    if (PyType_Ready(&PyHirschXLDContType) < 0)
        return;
    PyModule_AddObject(m, "HXLDCont", (PyObject *)&PyHirschXLDContType);
}

