// Autogenerated file for halcon type HXLDCont
#ifndef PYHXLDCONT_H
#define PYHXLDCONT_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschXLDCont_FromHXLDCont(HalconCpp::HXLDCont XLDCont);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HXLDCont *XLDCont;
} PyHirschXLDCont;

#define PyHirschXLDCont_Check(op) \
    PyObject_TypeCheck(op, &PyHirschXLDContType)

void PyHirschXLDContAddToModule(PyObject *m);

extern PyTypeObject PyHirschXLDContType;

#endif
