// Autogenerated file for halcon type HXLDArray
#ifndef PYHXLDARRAY_H
#define HXLDARRAY_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschXLDArray_FromHXLDArray(Halcon::HXLDArray XLDArray);

typedef struct {
    PyObject_HEAD;
    Halcon::HXLDArray *XLDArray;
} PyHirschXLDArray;

#define PyHirschXLDArray_Check(op) \
    PyObject_TypeCheck(op, &PyHirschXLDArrayType)

void PyHirschXLDArrayAddToModule(PyObject *m);

extern PyTypeObject  PyHirschXLDArrayType;

#endif
