// Autogenerated file for halcon type HXLD
#ifndef PYHXLD_H
#define PYHXLD_H

#include <Python.h>
#include <HalconCpp.h>

PyObject *PyHirschXLD_FromHXLD(HalconCpp::HXLD XLD);

typedef struct {
    PyObject_HEAD;
    HalconCpp::HXLD *XLD;
} PyHirschXLD;

#define PyHirschXLD_Check(op) \
    PyObject_TypeCheck(op, &PyHirschXLDType)

void PyHirschXLDAddToModule(PyObject *m);

PyAPI_DATA(PyTypeObject) PyHirschXLDType;

#endif
